[General]
Debug=1

[Server]
Host=127.0.0.1
Port=62031
Password=passw0rd
Housekeeping=1

[Homebrew]
KeepNodesAlive=1
NodeTimeout=1800
RelaxIPChange=1

[Monitor]
Enable=1
Port=8080
Root=www

[File]
Auth=auth_users.csv
DMRIds=DMRIds.dat
Log=log.sqlite
Talkgroup=talkgroup.dat
Banned=banned.dat

[DMR]
Scanner=777
Parrot=9990
APRS=900999

[Auth]
Enable=0
Reload=60
UnknownPolicy=0

[OpenBridge1]
Enable=1
Port=62044
TargetHost=127.0.0.1
TargetPort=62044
NetworkId=2161
Passphrase=passw0rd
ForceSlot1=0
PermitAll=0
PermitTGs=262,263,265,2626,26267,460,4000,46021,900999
EnhancedOBP=1
RelaxChecks=0
ResolveInterval=60

[OpenBridge2]
Enable=0

[OpenBridge3]
Enable=0

[APRS]
Enable=1
Server=cbaprs.dyndns.org
Port=14580
Callsign=DL0XYZ
Passcode=19366 
Filter=r/0/0/0
Keepalive=60
Reconnect=30
IdMap=aprs_map.csv

[SMS]
Enable=1
UDPHost=127.0.0.1
UDPPort=5555
AllowPrivate=1
PermitAll=1
PermitTGs=900999
MaxFrames=30
MaxSeconds=5
